"""added phone_no and name columns

Revision ID: 7cf50b05569d
Revises: e6a707197672
Create Date: 2026-05-31 11:37:30.192060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cf50b05569d'
down_revision = 'e6a707197672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('phone_no', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('phone_no', ['phone_no'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('phone_no')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
