"""add role column to users

Revision ID: 93565ac0a528
Revises: d9a37b06a2fa
Create Date: 2026-06-29 20:21:26.925326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93565ac0a528'
down_revision = 'd9a37b06a2fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, server_default='user'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
